//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCSWeb.WebPages
{


	public partial class _Warmup
	{

		/// <summary>
		/// lstWarningErrors control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::CCSWebControls.ErrorListView lstWarningErrors;

		/// <summary>
		/// divDebugInfo control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDebugInfo;

		/// <summary>
		/// btnDebugInfoToggleView control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button btnDebugInfoToggleView;

		/// <summary>
		/// txtDebugInfo control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox txtDebugInfo;

		/// <summary>
		/// Master property.
		/// </summary>
		/// <remarks>
		/// Auto-generated property.
		/// </remarks>
		public new CCSWeb.WebPages.ChartMaster Master
		{
			get
			{
				return ((CCSWeb.WebPages.ChartMaster)(base.Master));
			}
		}
	}
}
